name: 'Slack Notifier'
description: 'Action for sending push notifications to Slack'
inputs:
  status:
    description: 'The status of the job'
    required: true
  channel:
    description: 'The name of the slack channel'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
